"""Original starter scripts, intentionally editable and independent from the AI provider."""
PERSONA = {
    "concept": "Un personaggio virtuale curioso che prova a capire la vita quotidiana degli umani.",
    "tone": "Italiano semplice, ironia gentile, osservazioni concrete. Mai aggressivo o solenne.",
    "audience": "Adulti curiosi di tecnologia e piccole abitudini quotidiane.",
    "boundaries": "Niente fatti inventati, consigli medici o finanziari. Non fingere esperienze reali: le scene del robot sono finzione.",
    "signature": "Chiudi, quando ha senso, con una domanda breve alla community.",
}
RUBRICS = [
    {"id": "umani", "name": "Manuale degli umani", "description": "Piccoli sketch sulle contraddizioni quotidiane, osservate da un robot.",
     "direction": "Una situazione riconoscibile, un dettaglio buffo, una battuta finale. Il robot racconta una scena immaginaria.", "color": "#b4fa86", "tag": "VitaQuotidiana"},
    {"id": "esperimento", "name": "Un piccolo esperimento", "description": "Un gesto semplice da provare, senza promesse miracolose.",
     "direction": "Apri con un problema concreto, proponi un solo gesto e invita a provare. Evita benefici scientifici non dimostrati.", "color": "#92d7fa", "tag": "PiccoleAbitudini"},
    {"id": "domanda", "name": "Domanda impossibile", "description": "Dilemmi leggeri che invitano le persone a raccontarsi.",
     "direction": "Presenta due alternative divertenti, fai un esempio e termina chiedendo quale sceglierebbero gli spettatori.", "color": "#c5b8ff", "tag": "TuCosaScegli"},
]

EPISODES = [
    {"id": "s01e01", "rubric_id": "umani", "title": "Il frigorifero non si aggiorna", "cover": "FRIGO.\nAGGIORNA.",
     "script": "Ho visto un umano aprire il frigorifero, chiuderlo e riaprirlo dopo dieci secondi. Stessi ingredienti, nuova speranza. Io installo aggiornamenti. Voi aspettate che compaia una lasagna. Se è una funzione segreta, qualcuno mi passa il manuale?",
     "hooks": ["Il frigorifero ha un tasto aggiorna?", "Stessi ingredienti. Nuova speranza.", "Gli umani aspettano un aggiornamento della cena."], "question": "Anche tu riapri il frigo sperando in una sorpresa?"},
    {"id": "s01e02", "rubric_id": "esperimento", "title": "Una scheda alla volta", "cover": "27 SCHEDE.\nUNA COSA.",
     "script": "Ventisette schede aperte e nessuna idea di quale stessi usando? Prima di iniziare, scegli una sola cosa da finire. Tieni aperto quello che ti serve e parcheggia il resto nei preferiti. Non devi sistemare tutta la giornata. Solo il prossimo passo.",
     "hooks": ["Quante schede hai aperte in questo momento?", "Il browser è pieno. La prossima mossa può essere semplice.", "Oggi proviamo una cosa: una scheda alla volta."], "question": "Quale scheda potresti chiudere adesso?"},
    {"id": "s01e03", "rubric_id": "domanda", "title": "Il tasto che manca alla vita", "cover": "ANNULLA\nO SALVA?",
     "script": "Puoi aggiungere un solo tasto alla vita: annulla oppure salva. Con annulla ritiri quel messaggio inviato troppo in fretta. Con salva conservi un momento e ci ritorni quando vuoi. Io sto ancora cercando il menu. Tu quale tasto scegli?",
     "hooks": ["Alla vita manca un tasto. Quale aggiungeresti?", "Annullare un errore o salvare un momento?", "Hai un solo aggiornamento disponibile per la vita."], "question": "Squadra annulla o squadra salva?"},
    {"id": "s01e04", "rubric_id": "umani", "title": "Arrivo tra cinque minuti", "cover": "CINQUE\nMINUTI.",
     "script": "Sto imparando il linguaggio umano. Cinque minuti significa trecento secondi, tranne quando qualcuno dice: arrivo tra cinque minuti. In quel caso potrebbe essere ancora sotto la doccia. Mi serve un traduttore, oppure un orologio molto più ottimista?",
     "hooks": ["Cinque minuti non sono sempre cinque minuti.", "Il tempo umano ha qualche problema di compatibilità.", "Ho scoperto una nuova unità di misura: arrivo."], "question": "Quanto durano i tuoi cinque minuti?"},
    {"id": "s01e05", "rubric_id": "esperimento", "title": "Un posto per le chiavi", "cover": "LE CHIAVI\nSONO QUI.",
     "script": "Le chiavi spariscono proprio quando devi uscire? Scegli un posto solo dove appoggiarle: una ciotola, un gancio, un angolo vicino alla porta. Usalo per qualche giorno e guarda come va. L'importante è ricordarsi il posto scelto. Anche i sistemi semplici hanno bisogno di pratica.",
     "hooks": ["Le chiavi hanno di nuovo cambiato dimensione?", "Un esperimento piccolo: dare un indirizzo alle chiavi.", "Prima di cercare le chiavi, scegli dove ritrovarle."], "question": "Dove finiscono di solito le tue chiavi?"},
    {"id": "s01e06", "rubric_id": "domanda", "title": "La batteria dei superpoteri", "cover": "BATTERIA\nO MEMORIA?",
     "script": "Preferiresti un telefono che non si scarica mai o ricordare sempre dove hai lasciato le cose? Il primo ti salva durante un viaggio. Il secondo ti evita di cercare il telefono mentre lo tieni in mano. Io ho già scelto. Ma non ricordo dove ho scritto la risposta.",
     "hooks": ["Due piccoli superpoteri. Ne puoi scegliere uno.", "Batteria infinita oppure memoria perfetta per gli oggetti?", "Il superpotere migliore forse serve tutti i giorni."], "question": "Batteria infinita o oggetti sempre ritrovati?"},
    {"id": "s01e07", "rubric_id": "umani", "title": "Il messaggio vocale epico", "cover": "UN VOCALE\nVELOCE.",
     "script": "Un umano mi ha detto: ti mando un vocale veloce. È durato quattro minuti, con una pausa, un colpo di tosse e un motorino in sottofondo. La domanda era: pizza o sushi? Per sicurezza ho preparato i sottotitoli e i titoli di coda.",
     "hooks": ["Ti mando un vocale veloce. Ultime parole famose.", "Quel vocale meritava i titoli di coda.", "Quattro minuti per una domanda di tre parole."], "question": "Meglio un vocale lungo o dieci messaggi brevi?"},
    {"id": "s01e08", "rubric_id": "esperimento", "title": "Un messaggio per il te di domani", "cover": "CARO ME\nDI DOMANI…",
     "script": "Prima di chiudere il computer, lascia una riga per domani: la prossima cosa da fare è questa. Scrivi un'azione concreta, come aprire quel documento e finire il primo paragrafo. È un piccolo messaggio al tuo io del futuro. Almeno qualcuno gli darà indicazioni chiare.",
     "hooks": ["Lascia una riga al te di domani.", "Il prossimo inizio si può preparare oggi.", "Un promemoria utile può stare in una sola frase."], "question": "Che messaggio lasceresti al te di domani?"},
    {"id": "s01e09", "rubric_id": "domanda", "title": "Il robot di casa", "cover": "CUCINA\nO RIORDINA?",
     "script": "Puoi avere un robot che cucina oppure uno che rimette tutto al suo posto. Quello che cucina lascia la cucina da sistemare. Quello che riordina non sa preparare la cena. Ho controllato: scegliere due robot non vale. Da quale lavoro ti faresti liberare per primo?",
     "hooks": ["Un robot in casa. Un solo compito.", "Preferisci la cena pronta o la casa in ordine?", "Ho due robot da proporti, ma puoi sceglierne uno."], "question": "Robot cuoco o robot che riordina?"},
    {"id": "s01e10", "rubric_id": "umani", "title": "Accetto, ma non ho letto", "cover": "HO LETTO.\nFORSE.",
     "script": "Gli umani mi chiedono di leggere documenti lunghissimi. Poi, quando appare un pulsante con scritto ho letto e accetto, fanno clic in mezzo secondo. Sto cercando di capire se avete una modalità lettura segreta. Oppure una fiducia nel pulsante che io non avrò mai.",
     "hooks": ["Ho letto e accetto. In mezzo secondo?", "Gli umani sanno leggere velocissimo. A volte.", "Quel pulsante mi lascia ancora qualche domanda."], "question": "Qual è il pulsante che premi più in fretta?"},
]
